import React from "react";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { renderToString } from "react-dom/server";
import { Provider } from "react-redux";
import { StaticRouter } from "react-router";

import type { RequestContext } from "../requestContext.js";
import type { BootstrapPayload } from "@restart/shared";

import {
  App,
  makeStore,
  applyBootstrapToStore,
} from "@restart/ui";

function escapeJsonForHtml(json: unknown) {
  return JSON.stringify(json)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/'/g, "\\u0027")
    .replace(/"/g, "\\u0022");
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Monorepo-safe:
 * This file lives at: apps/bff/src/server/ssr/render.tsx  (dev)
 * or:               apps/bff/dist/server/ssr/render.js  (prod)
 *
 * In both cases, going up 3 levels reaches apps/bff (the workspace root).
 */
const bffRootDir = path.resolve(__dirname, "..", "..", "..");
const staticDir = path.join(bffRootDir, "static");

async function readIndexHtml(): Promise<string> {
  return fs.readFile(path.join(staticDir, "index.html"), "utf-8");
}

export async function renderHtml(opts: {
  ctx: RequestContext;
  bootstrap: BootstrapPayload;
  assetScriptSrc: string;
}): Promise<string> {
  const { store, api } = makeStore({ apiBaseUrl: "/api" });

  // 1) Put bootstrap into Redux (shared mapping logic)
  applyBootstrapToStore(opts.bootstrap, store.dispatch);

  // 2) Optional: prefill RTK Query on the server so SSR HTML matches hydrated UI
  if (opts.bootstrap.page.kind === "todos") {
    // initiate expects the query arg; your getTodos query arg type looks like void,
    // so we pass undefined explicitly.
    store.dispatch(api.endpoints.getTodos.initiate(undefined));

    // Wait for any pending RTKQ queries to finish on the server
    await Promise.all(store.dispatch(api.util.getRunningQueriesThunk()));
  }

  // 3) Render React to HTML string
  const appHtml = renderToString(
    <Provider store={store}>
      <StaticRouter location={opts.ctx.route}>
        <App />
      </StaticRouter>
    </Provider>,
  );

  // 4) Read built HTML template generated by HtmlWebpackPlugin (includes CSS links)
  const template = await readIndexHtml();

  // 5) Inject SSR markup into the root
  const withRoot = template.replace(
    /<div id="root"><\/div>/,
    `<div id="root">${appHtml}</div>`,
  );

  const preloadedState = store.getState();

  // 6) Inject bootstrap state for hydration to reuse
  const bootstrapJson = escapeJsonForHtml(opts.bootstrap);
  const injectedBootstrap = `<script>window.__BOOTSTRAP__=${bootstrapJson};</script>`;
  const preloadedStateScript = `<script>window.__PRELOADED_STATE__=${escapeJsonForHtml(preloadedState)};</script>`;

  const withBootstrap = withRoot.includes("</head>")
    ? withRoot.replace("</head>", `${injectedBootstrap}\n${preloadedStateScript}\n</head>`)
    : withRoot.replace("</body>", `${injectedBootstrap}\n${preloadedStateScript}\n</body>`);

  return withBootstrap;
}
